### ISSUE TITLE
Error in log file

### ISSUE THREAD

**Issue by DDB-en** [joesecurity/DocBleachShell#4]
Hi,
I'm using Office 2010, when i open .docx file this error log will be logged in tmp.log:
```
java.lang.UnsupportedClassVersionError: xyz/docbleach/cli/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Exception in thread "main" 
```

**Comment by joesecurity** [comment]
Hi ddheban,

That looks like an incompatibility of DocBleach with your installed version of Java. Version 52 seems to correspond to Java 8. https://stackoverflow.com/questions/10382929/

Hope this helps!
